------ My solution that worked
SELECT (MAX(EARN)), COUNT(*) FROM (SELECT SALARY*MONTHS AS EARN FROM EMPLOYEE) AS T WHERE EARN = (SELECT MAX(SALARY*MONTHS) FROM EMPLOYEE)

-- 108064 7

---- Others' solution
SELECT SALARY*MONTHS AS EARNINGS, COUNT(*) FROM EMPLOYEE
GROUP BY EARNINGS
ORDER BY EARNINGS DESC LIMIT 1;

---- Shorter solution
SELECT SALARY*MONTHS AS EARNINGS, COUNT(*) FROM EMPLOYEE
GROUP BY EARNINGS DESC LIMIT 1;

---- Even shorter
SELECT SALARY*MONTHS AS EARNINGS, COUNT(*) FROM EMPLOYEE
GROUP BY 1 DESC LIMIT 1;