----- OK -----
SELECT ROUND(SQRT(POWER(MAXLT-MINLT, 2) + POWER(MAXLG-MINLG, 2)), 4) FROM (SELECT MIN(LAT_N) AS MINLT, MAX(LAT_N) AS MAXLT, MIN(LONG_W) AS MINLG, MAX(LONG_W) AS MAXLG FROM STATION) AS T

----- Shorter -----
SELECT ROUND(SQRT(POWER(MAX(LAT_N)-MIN(LAT_N), 2) + POWER(MAX(LONG_W)-MIN(LONG_W), 2)), 4) FROM STATION